"""init

Revision ID: 3de076c6d73a
Revises: bb1625cd3b83
Create Date: 2023-06-01 17:05:25.230703

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "3de076c6d73a"
down_revision = "bb1625cd3b83"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
