"""init

Revision ID: bb1625cd3b83
Revises: cc5a2cdddcab
Create Date: 2023-06-01 17:03:06.315523

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb1625cd3b83"
down_revision = "cc5a2cdddcab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
